### PR TITLE
Defer hibernate sequence DML to after DDL batch

### LINKED ISSUE #171: Batched DDL fails for creating the Hibernate Sequence table
If hibernate attempts to create a sequence table, it will fail because it will include [the DML statement which inserts a single row](https://github.com/GoogleCloudPlatform/google-cloud-spanner-hibernate/blob/master/google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/SpannerTableExporter.java#L98) into the DDL batch.

### PR DESCRIPTION
**Pull request by dzou**
This PR modifies the `INSERT` statement used for creating the hibernate_sequence table by deferring it until after the DDL batch is complete.

Fixes #171

### CODE REVIEW

File: google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerTableStatements.java [hunk 1]
```diff
@@ -158,10 +162,22 @@ private boolean isElementCollection(Table table, Metadata metadata) {
...
+              .map(obj -> (RunBatchDdl) obj)
+              .findFirst();
+
+      if (runBatchDdl.isPresent()) {
+        RunBatchDdl runBatchObj = runBatchDdl.get();
+        runBatchObj.addAfterDdlStatement(
+            "INSERT INTO " + SequenceStyleGenerator.DEF_SEQUENCE_NAME + " ("
+                + SequenceStyleGenerator.DEF_VALUE_COLUMN + ") VALUES(1)");
+      } else {
+        LOGGER.warn("Failed to insert the first row into the Hibernate sequence table.");
```
Comment (meltsufin) [inline google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerTableStatements.java]: Shouldn't you fail hard here because `runbBatchDdl` object is not present? It's not that you were not able to insert the row.

File: google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerTableStatements.java [hunk 2]
```diff
@@ -158,10 +162,22 @@ private boolean isElementCollection(Table table, Metadata metadata) {
 
     statements.add(createTableString);
 
-    // Hibernate requires the special hibernate_sequence table to be populated with an initial val.
     if (table.getName().equals(SequenceStyleGenerator.DEF_SEQUENCE_NAME)) {
-      statements.add("INSERT INTO " + SequenceStyleGenerator.DEF_SEQUENCE_NAME + " ("
-          + SequenceStyleGenerator.DEF_VALUE_COLUMN + ") VALUES(1)");
+      // Caches the INSERT statement in the RunBatchDdl auxiliary object.
+      Optional<RunBatchDdl> runBatchDdl =
```
Comment (meltsufin) [inline google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerTableStatements.java]: Maybe create a separate `findRunBatchDdl` method for clarity?

File: google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerTableStatements.java (hunk 1 above)
Comment (dzou) [reply google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerTableStatements.java]: Done. It now throws an exception; if this occurs this mean there is some edge case we missed so I added a message to report it as an issue.

File: google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerTableStatements.java (hunk 2 above)
Comment (dzou) [reply google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerTableStatements.java]: Done.

File: google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/RunBatchDdl.java [hunk 3]
```diff
@@ -31,8 +33,23 @@
...
+   * @param schemaAction the DDL mode being used for schema generation.
+   */
   public RunBatchDdl(Action schemaAction) {
     this.schemaAction = schemaAction;
+    this.statements = new ArrayList<>();
+    this.statements.add("RUN BATCH");
+  }
+
+  /**
+   * Add a statement to run after the DDL batch is completed.
```
Comment (elefeint) [inline google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/RunBatchDdl.java]: I'd add a comment for why this may be necessary.

File: google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerTableStatements.java [hunk 4]
```diff
@@ -158,15 +162,36 @@ private boolean isElementCollection(Table table, Metadata metadata) {
 
     statements.add(createTableString);
 
-    // Hibernate requires the special hibernate_sequence table to be populated with an initial val.
     if (table.getName().equals(SequenceStyleGenerator.DEF_SEQUENCE_NAME)) {
-      statements.add("INSERT INTO " + SequenceStyleGenerator.DEF_SEQUENCE_NAME + " ("
-          + SequenceStyleGenerator.DEF_VALUE_COLUMN + ") VALUES(1)");
+      // Caches the INSERT statement for after the DDL batch.
```
Comment (elefeint) [inline google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerTableStatements.java]: leave a few words for why this is needed

File: google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerTableStatements.java [hunk 5]
```diff
@@ -158,15 +162,36 @@ private boolean isElementCollection(Table table, Metadata metadata) {
...
+      addStatementAfterDdlBatch(
+          metadata,
+          "INSERT INTO " + SequenceStyleGenerator.DEF_SEQUENCE_NAME + " ("
```
Comment (elefeint) [inline google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerTableStatements.java]: Not actionable for this PR: even though table creation/update/deletion are not frequent or high-volume operations, the amount of string concatenation (which is slow and creates intermediate literals) is starting to be concerning.
Is that typical for Hibernate and its dialects?

File: google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/RunBatchDdl.java (hunk 3 above)
Comment (dzou) [reply google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/RunBatchDdl.java]: Done.

File: google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerTableStatements.java (hunk 4 above)
Comment (dzou) [reply google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerTableStatements.java]: Done.

File: google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerTableStatements.java (hunk 5 above)
Comment (dzou) [reply google-cloud-spanner-hibernate-dialect/src/main/java/com/google/cloud/spanner/hibernate/schema/SpannerTableStatements.java]: Good point, looks like Hibernate uses `StringBuilder` in their code instead of string concatenation. We can definitely switch to this style in the future.

I created an issue to track this: #182

**Comment by dzou** [comment]
> Semi-related question that I am too lazy to find the answer to -- Does hibernate_sequence get deleted on DROP?

Yes! it does get deleted on drop.
